# frozen_string_literal: true
source 'https://rubygems.org'

gemspec path: '../..'

group :development do
  gem 'rails', '~> 8.0.0'

  gem 'mocha', '~> 2.8' # TODO: relax this dependency after fixing #981
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'rails-controller-testing'
  gem 'simplecov', require: false
  gem 'simplecov-cobertura'
  gem 'warning'
end
