version: 2
multi-ecosystem-groups:
  bundler:
    schedule:
      interval: monthly
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github_actions:
        patterns:
          - "*"
  - package-ecosystem: bundler
    directory: /
    versioning-strategy: lockfile-only
    patterns:
      - "*"
    multi-ecosystem-group: bundler
  - package-ecosystem: bundler
    directory: /gemfiles/rails_70
    versioning-strategy: lockfile-only
    patterns:
      - "*"
    multi-ecosystem-group: bundler
    ignore:
      - dependency-name: minitest
        versions: ">= 6.0.0"
      - dependency-name: rails
        versions: ">= 7.1.0"
      - dependency-name: railties
        versions: ">= 7.1.0"
  - package-ecosystem: bundler
    directory: /gemfiles/rails_71
    versioning-strategy: lockfile-only
    patterns:
      - "*"
    multi-ecosystem-group: bundler
    ignore:
      - dependency-name: erb
        versions: ">= 5"
      - dependency-name: minitest
        versions: ">= 6.0.0"
      - dependency-name: rails
        versions: ">= 7.2.0"
      - dependency-name: railties
        versions: ">= 7.2.0"
  - package-ecosystem: bundler
    directory: /gemfiles/rails_72
    versioning-strategy: lockfile-only
    patterns:
      - "*"
    multi-ecosystem-group: bundler
    ignore:
      - dependency-name: erb
        versions: ">= 5"
      - dependency-name: minitest
        versions: ">= 6.0.0"
      - dependency-name: rails
        versions: ">= 8.0.0"
      - dependency-name: railties
        versions: ">= 8.0.0"
  - package-ecosystem: bundler
    directory: /gemfiles/rails_80
    versioning-strategy: lockfile-only
    patterns:
      - "*"
    multi-ecosystem-group: bundler
    ignore:
      - dependency-name: rails
        versions: ">= 8.1.0"
      - dependency-name: railties
        versions: ">= 8.1.0"
