---

pull_request_rules:
  - name: Automatic merge for dependabot pull requests

    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=lint
      - check-success=test(ruby-2.7, rails_60)
      - check-success=test(ruby-2.7, rails_61)
      - check-success=test(ruby-2.7, rails_70)
      - check-success=test(ruby-3.0, rails_60)
      - check-success=test(ruby-3.0, rails_61)
      - check-success=test(ruby-3.0, rails_70)
      - check-success=test(ruby-3.1, rails_60)
      - check-success=test(ruby-3.1, rails_61)
      - check-success=test(ruby-3.1, rails_70)

    actions:
      merge:
        method: merge
