# https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default
ignore: |
  tmp/
  vendor/
rules: # https://yamllint.readthedocs.io/en/stable/rules.html
  comments:
    min-spaces-from-content: 1
  document-start: disable
  line-length: disable
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "on"
      - "off"
