source 'https://rubygems.org'

gemspec path: '../..'

group :development do
  gem 'rails', '~> 5.2.a'

  gem 'mocha'
  gem 'minitest-rg'
  gem 'rails-controller-testing', github: 'rails/rails-controller-testing', ref: 'a60b3da1c1c77959b28606dd087c058c64b5a08f'
  gem 'chandler', '0.9.0'
end
