source 'https://rubygems.org'

gemspec path: '../..'

group :development do
  gem 'rails', '~> 5.1.a'

  gem 'mocha'
  gem 'minitest-rg'
  gem 'rails-controller-testing'
  gem 'rubocop'
  gem 'chandler', '0.9.0'
end
