# frozen_string_literal: true
source 'https://rubygems.org'

gemspec path: '../..'

group :development do
  gem 'rails', '~> 7.2.0'

  gem 'mocha'
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'rails-controller-testing'
  gem 'rbs', '~> 4.1.0' # TODO: remove when dropping Ruby < 3.3 compatibility
  gem 'simplecov', require: false
  gem 'simplecov-cobertura'
  gem 'warning'
end
