# frozen_string_literal: true
source 'https://rubygems.org'

gemspec path: '../..'

group :development do
  gem 'rails', '~> 7.2.0'
  # Rails 7.2.4 caps connection_pool below 3, whose keyword-argument API breaks cache stores
  gem 'connection_pool', '< 3' # TODO: remove when dropping Rails 7.2 (see rails/rails#56620)

  gem 'mocha'
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'rails-controller-testing'
  gem 'rbs', '~> 4.1.0' # TODO: remove when dropping Ruby < 3.3 compatibility
  gem 'simplecov', require: false
  gem 'simplecov-cobertura'
  gem 'warning'
end
