source 'https://rubygems.org'

gemspec path: '../..'

group :development do
  gem 'rails', '~> 6.1.0'

  gem 'mocha'
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'rails-controller-testing'
  gem 'simplecov', require: false
  gem 'simplecov-cobertura'
  gem 'warning'
end
